version: '2'
services:

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clikhouse
    ports:
      - 8123:8123

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27012:27017

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-stand
    volumes:
      - '.:/var/app'

